// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2da2f6bc-64e4-4c64-b0d7-30113fd246be",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HwiGNbaDc",
    "aws_user_pools_web_client_id": "7ve27tb642l965fj0vnngh9dl4",
    "aws_appsync_graphqlEndpoint": "https://ekm6fg4dcrfa5olovw7joczefq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-q6wyx3ufbnfdpfct5o7obr5z6a"
};


export default awsmobile;
